In [3]:
import torch
import pickle
import scipy

In [ ]:
with open('data/fb/adj_orig_dense_list.pickle', 'rb') as handle:
    adj_orig_dense_list = pickle.load(handle)
torch.save(adj_orig_dense_list, 'data/fb/adj_orig_dense_list.pt', pickle_protocol=2)

In [ ]:
import joblib
import pickle  # only for loading the original
topic = 'enron10'
with open('data/' + topic + '/adj_time_list.pickle', 'rb') as f:
    adj_time_list = pickle.load(f)

joblib.dump(adj_time_list, 'data/'+ topic + '/adj_time_list.joblib', compress=3)

['data/enron10/adj_time_list.joblib']

In [13]:
import joblib
# Facebook dataset
# with open('data/fb/adj_time_list.pt', 'rb') as handle:
#     adj_time_list = pickle.load(handle, encoding='latin1')
topic = 'edca/noncumulative'
adj_time_list = joblib.load(f'data/{topic}/adj_time_list.joblib')

torch.save(adj_time_list, f'data/{topic}/adj_time_list.pt')

In [ ]:
# with open('data/'+topic+'/adj_orig_dense_list.pickle', 'rb') as handle:
#     adj_orig_dense_list = pickle.load(handle)
# joblib.dump(adj_orig_dense_list, 'data/'+ topic + '/adj_orig_dense_list.joblib', compress=3)

with open('data/' + topic + '/adj_orig_dense_list.pickle', 'rb') as handle:
    adj_orig_dense_list = pickle.load(handle)
torch.save(adj_orig_dense_list, 'data/' + topic + '/adj_orig_dense_list.pt', pickle_protocol=2)

In [10]:
torch.load(f'data/{topic}/adj_orig_dense_list.pt')
torch.load(f'data/{topic}/adj_time_list.pt', weights_only=False)

[<Compressed Sparse Row sparse array of dtype 'int64'
 	with 322 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 2282 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 2770 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 3830 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 7206 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 8586 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 9066 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 9808 stored elements and shape (1379, 1379)>,
 <Compressed Sparse Row sparse array of dtype 'int64'
 	with 9832 stored elements and shape (1379, 1379)>]

In [20]:
adj_orig_dense_list

[tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [21]:
adj_time_list

[<184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 230 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 312 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 424 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 446 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 358 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 530 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 480 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 506 stored elements in Compressed Sparse Row format>,
 <184x184 sparse matrix of type '<type 'numpy.uint8'>'
 	with 490 stored